# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: ko

# Site title
title: "Doona's Blog"

# A description of your site for meta tag, search engine results.
description: "사진, 그림, 수다를 좋아하며 듣기, 게으름피우기, 여럿이 함께 놀기를 잘하는 풀스택 개발자입니다. 영어 이름은 Skyler 입니다."

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://skyler85.github.io/"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Style Guide
    url: /style-guide
  - text: Tags
    url: /tags
  - text: Download
    url: https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme

# The shortname for your Disqus site to enable comments.
disqus: justgoodthemes

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; Scriptor all rights reserved. Theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
